name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Generate release notes
        id: release_notes
        run: |
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md
          echo "Release ${{ steps.version.outputs.version }} of the GitHub Projects Iteration Rollover Action." >> release_notes.md
          echo "" >> release_notes.md
          echo "### Usage" >> release_notes.md
          echo '```yaml' >> release_notes.md
          echo "- uses: kriscoleman/gh-projects-action@${{ steps.version.outputs.version }}" >> release_notes.md
          echo "  with:" >> release_notes.md
          echo "    project_url: 'https://github.com/users/USERNAME/projects/NUMBER'" >> release_notes.md
          echo '```' >> release_notes.md
          echo "" >> release_notes.md
          echo "See the [README](https://github.com/kriscoleman/gh-projects-action/blob/main/README.md) for full documentation." >> release_notes.md
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true